### ISSUE TITLE
Add date/number functions to core

### ISSUE THREAD

**Issue by danielkcz** [huan086/lingui-typings#1]
Similar to React components, there are these two functions on the core `i18n`. Documentation is missing, but it's kinda obvious how it works. Can you add to typings please?

https://github.com/lingui/js-lingui/commit/82d7328f4e315f035783bce84c8f1b5db838f0a4

**Comment by huan086** [comment]
New version encourages `@lingui/macro` instead

**Comment by danielkcz** [comment]
I don't follow why to close this. Sure I know about macros, but that's missing typings completely. The function on the core won't go away, they are still usable in environments without macros.
